source 'https://cdn.cocoapods.org/'

target 'ShapesApp' do
  use_frameworks!
  platform :ios, '12.0'
  pod 'approov-service-nsurlsession', '3.3.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
