source 'https://cdn.cocoapods.org/'

target 'ShapesApp' do
  use_frameworks!
  platform :ios, '15.0'
  pod 'approov-service-nsurlsession', '3.5.3'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      # Xcode 27 supports iOS deployment targets starting at 15.0.
      target_version = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      if target_version.nil? || Gem::Version.new(target_version) < Gem::Version.new('15.0')
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end
